CREATE TABLE IF NOT EXISTS Skins(
    key TEXT PRIMARY KEY,
    opened INTEGER NOT NULL,
    chosen INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Progress(
    id INTEGER PRIMARY KEY CHECK(id = 1),
    money INTEGER NOT NULL,
    level INTEGER NOT NULL
);
