CREATE TABLE IF NOT EXISTS Players(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

INSERT OR IGNORE INTO Players(id,name) VALUES (1,'Default');

CREATE TABLE IF NOT EXISTS Skins(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS PlayerProgress(
    player_id INTEGER PRIMARY KEY,
    money INTEGER NOT NULL,
    level INTEGER NOT NULL,
    FOREIGN KEY(player_id) REFERENCES Players(id) ON DELETE CASCADE
);

INSERT OR IGNORE INTO PlayerProgress(player_id,money,level) VALUES(1,0,1);

CREATE TABLE IF NOT EXISTS PlayerSkins(
    player_id INTEGER NOT NULL,
    skin_id INTEGER NOT NULL,
    opened INTEGER NOT NULL,
    chosen INTEGER NOT NULL,
    PRIMARY KEY(player_id, skin_id),
    FOREIGN KEY(player_id) REFERENCES Players(id) ON DELETE CASCADE,
    FOREIGN KEY(skin_id) REFERENCES Skins(id) ON DELETE CASCADE
);
